export interface Quote {
  text: string;
  author: string;
}

export const COMMAND_QUOTES: Quote[] = [
  // --- SPIRITUEL & FOI INÉBRANLABLE ---
  { text: "Prie comme si tout dépendait de Dieu. Travaille comme si tout dépendait de toi.", author: "Saint Augustin" },
  { text: "Je puis tout par celui qui me fortifie. Aucune fatigue humaine ne surpasse la grâce divine.", author: "Philippiens 4:13" },
  { text: "Ce n'est pas par la force, ni par la puissance, mais par mon Esprit, dit l'Éternel des armées.", author: "Zacharie 4:6" },
  { text: "Quand je marche dans la vallée de l'ombre de la mort, je ne crains aucun mal, car tu es avec moi.", author: "Psaume 23:4" },
  { text: "Ceux qui se confient en l'Éternel renouvellent leur force. Ils prennent le vol comme les aigles.", author: "Ésaïe 40:31" },
  { text: "Dieu ne nous a pas donné un esprit de timidité, mais de force, d'amour et de sagesse.", author: "2 Timothée 1:7" },
  { text: "La prière n'est pas un bouton d'urgence, c'est le volant de toute ta vie.", author: "Charles Spurgeon" },
  { text: "L'homme qui s'agenouille devant Dieu peut tenir debout devant n'importe qui et n'importe quoi.", author: "A.W. Tozer" },
  { text: "Ne prie pas pour des tâches faciles. Prie pour avoir des épaules plus fortes.", author: "Phillips Brooks" },
  { text: "La foi consiste à faire le premier pas même quand on ne voit pas tout l'escalier.", author: "Martin Luther King Jr." },
  { text: "Si Dieu est pour nous, qui sera contre nous ? Rien ne t'arrêtera si ta mission est alignée.", author: "Romains 8:31" },
  { text: "Celui qui habite sous l'abri du Très-Haut repose à l'ombre du Tout-Puissant.", author: "Psaume 91:1" },
  { text: "Demandez et l'on vous donnera, cherchez et vous trouverez, frappez et l'on vous ouvrira.", author: "Matthieu 7:7" },
  { text: "L'épreuve de votre foi produit la patience. Et il faut que la patience accomplisse parfaitement son œuvre.", author: "Jacques 1:3-4" },
  { text: "Le combat spirituel précède toujours la victoire matérielle. Gagne dans le secret de ta chambre.", author: "Aegis Flow" },

  // --- RÉSILIENCE & MORAL À ZÉRO ---
  { text: "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.", author: "Winston Churchill" },
  { text: "Si tu traverses l'enfer, continue d'avancer. Pourquoi t'arrêterais-tu en enfer ?", author: "Winston Churchill" },
  { text: "La gloire n'est pas de ne jamais tomber, mais de se relever chaque fois que nous tombons.", author: "Confucius" },
  { text: "C'est dans les moments les plus sombres que l'on doit se concentrer pour voir la lumière.", author: "Aristote Onassis" },
  { text: "Le courage n'est pas l'absence de peur, mais la capacité de la vaincre.", author: "Nelson Mandela" },
  { text: "La douleur que tu ressens aujourd'hui est la force que tu ressentiras demain.", author: "David Goggins" },
  { text: "Quand tu as envie d'abandonner, rappelle-toi pourquoi tu as commencé.", author: "Nietzsche" },
  { text: "Il n'y a pas de passion à jouer petit et à se contenter d'une vie inférieure à ce dont on est capable.", author: "Nelson Mandela" },
  { text: "Ce qui ne me tue pas me rend plus fort. Ton moral à zéro est la fondation de ta renaissance.", author: "Friedrich Nietzsche" },
  { text: "Personne ne se soucie de ta fatigue. Lève-toi et exécute ce qui doit être fait.", author: "Jocko Willink" },
  { text: "Les obstacles sont ces choses effrayantes que tu aperçois quand tu détournes les yeux de ton but.", author: "Henry Ford" },
  { text: "Le moment où tu es prêt à abandonner est généralement le moment juste avant le miracle.", author: "Sagesse Anonyme" },
  { text: "Le feu teste l'or, l'adversité teste les hommes forts.", author: "Sénèque" },
  { text: "Ne pleure pas pour abandonner. Pleure pour continuer. Tu as déjà souffert, obtiens ta récompense !", author: "Eric Thomas" },
  { text: "Même la nuit la plus sombre prend fin et le soleil se lève toujours.", author: "Victor Hugo" },
  { text: "Tu es plus fort que tu ne le penses, plus capable que tu ne l'imagines, et plus proche que tu ne le crois.", author: "Aegis Flow" },
  { text: "L'endurance n'est pas seulement la capacité de supporter une chose difficile, mais de la transformer en gloire.", author: "William Barclay" },
  { text: "Ton esprit abandonne toujours 100 fois avant ton corps. Prends le contrôle de ton esprit.", author: "David Goggins" },
  { text: "Le désespoir est une illusion tactique de l'ennemi. Rebranche-toi à ta mission.", author: "Aegis Flow" },
  { text: "La nuit est toujours plus sombre juste avant l'aube. Tiens bon, l'aube arrive.", author: "Thomas Fuller" },

  // --- DISCIPLINE & EXECUTION BRUTALE ---
  { text: "La discipline est le pont entre les objectifs et les réalisations. Il n'y a pas de raccourci.", author: "Jim Rohn" },
  { text: "Nous sommes ce que nous faisons de manière répétée. L'excellence n'est donc pas un acte, mais une habitude.", author: "Aristote" },
  { text: "Les amateurs s'assoient et attendent l'inspiration, les autres se lèvent et vont au travail.", author: "Stephen King" },
  { text: "Que l'on me donne six heures pour abattre un arbre, j'en passerai quatre à aiguiser ma hache.", author: "Abraham Lincoln" },
  { text: "Ne crains pas d'avancer lentement, crains seulement de t'arrêter.", author: "Sagesse Millénaire" },
  { text: "L'obsédé bat toujours le talentueux. 210 jours de concentration laser redéfiniront toute ton existence.", author: "Aegis Flow" },
  { text: "La discipline pèse des onces, le regret pèse des tonnes.", author: "Jim Rohn" },
  { text: "Fais ce que tu dois faire, quand tu dois le faire, que tu en aies envie ou non.", author: "Thomas Huxley" },
  { text: "Si tu ne sacrifies pas pour ce que tu veux, ce que tu veux devient le sacrifice.", author: "Sagesse Anonyme" },
  { text: "Le succès est la somme de petits efforts répétés jour après jour.", author: "Robert Collier" },
  { text: "La motivation te fait débuter, mais c'est la discipline qui te fait continuer.", author: "Jim Ryun" },
  { text: "Rien de grand ne s'est jamais accompli sans passion et sans une exécution implacable.", author: "Hegel" },
  { text: "Le talent sans discipline ressemble à une pieuvre sur des patins à roulettes.", author: "H. Jackson Brown Jr." },
  { text: "On ne négocie pas avec la discipline. Elle est absolue ou elle n'est pas.", author: "Aegis Flow" },
  { text: "La différence entre le possible et l'impossible réside dans la détermination de l'homme.", author: "Tommy Lasorda" },
  { text: "Chaque action que tu fais est un vote pour le type de personne que tu souhaites devenir.", author: "James Clear" },
  { text: "Domine ton matin, domine ta journée. Pas d'excuse, pas de compromis.", author: "Robin Sharma" },
  { text: "Sois tellement occupé à t'améliorer que tu n'as pas le temps de prêter attention aux distractions.", author: "Sagesse Anonyme" },
  { text: "L'effort ne ment jamais. Les chiffres et les clients suivront le travail brut.", author: "Aegis Flow" },
  { text: "Le travail acharné bat le talent quand le talent ne travaille pas durement.", author: "Tim Notke" },

  // --- SAAS, TECH & VISION BUSINESS ---
  { text: "Construis un monopole technologique en créant une valeur 10x supérieure à tout le reste.", author: "Peter Thiel" },
  { text: "Si tu n'as pas honte de la première version de ton produit, c'est que tu l'as lancé trop tard.", author: "Reid Hoffman" },
  { text: "La meilleure façon de prédire l'avenir est de le créer ligne de code par ligne de code.", author: "Peter Drucker" },
  { text: "Fais des offres tellement irrésistibles que les gens se sentiraient stupides de dire non.", author: "Alex Hormozi" },
  { text: "Les clients ne mesurent pas tes efforts, ils mesurent la transformation que tu leur apportes.", author: "Aegis Flow" },
  { text: "Focus sur le mouvement d'audience et la conversion. Le reste n'est que littérature.", author: "Russell Brunson" },
  { text: "Ton objectif n'est pas de créer une entreprise, mais de résoudre un problème pour 100 000 personnes.", author: "Aegis Flow" },
  { text: "Le code est ta loi, le MRR est ton oxygène, la satisfaction client est ton héritage.", author: "Aegis Flow" },
  { text: "Les idées sont des commodités. L'exécution de qualité production est ce qui génère des millions.", author: "Michael Dell" },
  { text: "Ne cherche pas des clients pour tes produits, cherche des produits pour tes clients.", author: "Seth Godin" },
  { text: "Le marché se moque de tes sentiments. Il ne récompense que la valeur extrême livrée avec rapidité.", author: "Aegis Flow" },
  { text: "Itère rapidement. Mesure tout. N'aie pas peur de pivoter vers ce qui convertit massivement.", author: "Eric Ries" },
  { text: "Un entrepreneur est quelqu'un qui saute d'une falaise et construit un avion en tombant.", author: "Reid Hoffman" },
  { text: "Dans le monde de la tech, le plus grand risque est de ne prendre aucun risque.", author: "Mark Zuckerberg" },
  { text: "Le succès d'un SaaS dépend de sa capacité à transformer un clic en une habitude quotidienne.", author: "Nir Eyal" },
  { text: "La simplicité est la sophistication suprême pour une interface utilisateur.", author: "Léonard de Vinci" },
  { text: "Ne célèbre pas l'acquisition, célèbre la rétention. C'est là que réside la vraie valeur.", author: "Aegis Flow" },
  { text: "Chaque bug corrigé, chaque feature livrée te rapproche des 100 000 clients payants.", author: "Aegis Flow" },
  { text: "La clarté du pitch et la vélocité du code sont les deux piliers d'une croissance explosive.", author: "Aegis Flow" },
  { text: "Si tu veux atteindre 100 000 clients, tu dois d'abord en enchanter 10 avec obsession.", author: "Paul Graham" },

  // --- MENTAL TOUGHNESS & GUERRIER INTÉRIEUR ---
  { text: "Tu ne peux pas blesser un homme qui n'a plus rien à perdre et tout à prouver à lui-même.", author: "David Goggins" },
  { text: "Souviens-toi que tu vas mourir. C'est le meilleur moyen d'éviter le piège de croire que tu as quelque chose à perdre.", author: "Steve Jobs" },
  { text: "L'inconfort est la devise de ta croissance. Achète ton futur avec ta sueur d'aujourd'hui.", author: "Aegis Flow" },
  { text: "Ne souhaite pas que ce soit plus facile, souhaite être meilleur.", author: "Jim Rohn" },
  { text: "L'arène ne pardonne pas aux faibles, mais elle couronne ceux qui refusent d'abandonner.", author: "Aegis Flow" },
  { text: "Ce que tu obtiens en atteignant tes objectifs n'est pas aussi important que ce que tu deviens en les atteignant.", author: "Zig Ziglar" },
  { text: "Le calme dans la tempête est la marque des grands capitaines.", author: "Sagesse Anonyme" },
  { text: "La souffrance est temporaire. L'abandon dure pour l'éternité.", author: "Lance Armstrong" },
  { text: "Un homme fort n'est pas celui qui ne pleure pas, mais celui qui pleure, sèche ses larmes et reprend le combat.", author: "Sagesse Orientale" },
  { text: "Ton corps peut tout supporter. C'est ton esprit que tu dois convaincre chaque matin à 5h.", author: "Aegis Flow" },
  { text: "Le doute tue plus de rêves que l'échec ne le fera jamais.", author: "Suzy Kassem" },
  { text: "Ce n'est pas la montagne que nous surmontons, mais nous-mêmes.", author: "Edmund Hillary" },
  { text: "Celui qui n'a pas le courage de prendre des risques n'accomplira rien dans sa vie.", author: "Muhammad Ali" },
  { text: "Le monde fait place à l'homme qui sait exactement où il va.", author: "Ralph Waldo Emerson" },
  { text: "Sois le maître de ton destin, le capitaine de ton âme.", author: "William Ernest Henley" },
  { text: "Quand tout semble être contre toi, souviens-toi que l'avion décolle face au vent, pas avec lui.", author: "Henry Ford" },
  { text: "Ne t'arrête pas quand tu es fatigué. Arrête-toi quand tu as terminé.", author: "David Goggins" },
  { text: "Tu es le seul auteur de ton histoire. Ne donne la plume à personne d'autre.", author: "Aegis Flow" },
  { text: "La victoire appartient à celui qui est le plus persévérant.", author: "Napoléon Bonaparte" },
  { text: "Si tu veux des résultats que 99% des gens n'ont pas, tu dois faire ce que 99% des gens refusent de faire.", author: "Aegis Flow" },

  // --- SAGESSE & PERSPECTIVE DE VIE ---
  { text: "Le meilleur moment pour planter un arbre était il y a 20 ans. Le deuxième meilleur moment est maintenant.", author: "Proverbe Chinois" },
  { text: "La folie, c'est de faire toujours la même chose et de s'attendre à un résultat différent.", author: "Albert Einstein" },
  { text: "Le secret du changement consiste à concentrer toute son énergie non pas à lutter contre le passé, mais à construire l'avenir.", author: "Socrate" },
  { text: "La vie ce n'est pas d'attendre que les orages passent, c'est d'apprendre à danser sous la pluie.", author: "Sénèque" },
  { text: "Il n'y a qu'une seule façon d'éviter les critiques : ne rien faire, ne rien dire, et n'être rien.", author: "Aristote" },
  { text: "Votre temps est limité, ne le gâchez pas en menant une existence qui n'est pas la vôtre.", author: "Steve Jobs" },
  { text: "Celui qui veut réussir trouve un moyen. Celui qui ne veut rien faire trouve une excuse.", author: "Proverbe" },
  { text: "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information.", author: "Albert Einstein" },
  { text: "Il est difficile d'échouer, mais il est encore pire de n'avoir jamais tenté de réussir.", author: "Theodore Roosevelt" },
  { text: "Le bonheur n'est pas quelque chose de tout fait. Il découle de vos propres actions.", author: "Dalaï Lama" },
  { text: "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.", author: "Gandhi" },
  { text: "Exige beaucoup de toi-même et attends peu des autres. Ainsi beaucoup d'ennuis te seront épargnés.", author: "Confucius" },
  { text: "Plus le combat est difficile, plus la victoire est belle.", author: "Thomas Paine" },
  { text: "N'attends pas que les conditions soient parfaites pour commencer. Le commencement rend les conditions parfaites.", author: "Alan Cohen" },
  { text: "Rien n'est permanent dans ce monde vicieux, pas même nos problèmes.", author: "Charlie Chaplin" },
  { text: "La seule limite à notre épanouissement de demain sera nos doutes d'aujourd'hui.", author: "Franklin D. Roosevelt" },
  { text: "Un voyage de mille lieues commence toujours par un premier pas.", author: "Lao Tseu" },
  { text: "Ce ne sont pas les années dans ta vie qui comptent. C'est la vie dans tes années.", author: "Abraham Lincoln" },
  { text: "L'échec est seulement l'opportunité de recommencer d'une façon plus intelligente.", author: "Henry Ford" },
  { text: "Ne compare pas ton chapitre 1 au chapitre 20 de quelqu'un d'autre. Reste dans ton couloir.", author: "Aegis Flow" },

  // --- COMMAND CENTER EXCLUSIVE (AEGIS DIRECTIVES) ---
  { text: "Aujourd'hui est une page vierge. Ton code, tes prières et ton focus en écriront la légende.", author: "Aegis Flow" },
  { text: "L'anxiété se dissout dans l'action immédiate. Cesse de penser, commence à exécuter.", author: "Aegis Flow" },
  { text: "Le cap des 100 000 clients n'est pas un rêve, c'est une équation mathématique de valeur et de persévérance.", author: "Aegis Flow" },
  { text: "Ton niveau d'anglais ouvrira les portes du marché mondial. Ne sous-estime jamais tes 45 minutes du jour.", author: "Aegis Flow" },
  { text: "Un pitch parfait est une symphonie de conviction et de clarté. Répète jusqu'à l'obsession.", author: "Aegis Flow" },
  { text: "100 livres en 7 mois représentent le téléchargement de la sagesse des plus grands esprits de l'humanité.", author: "Aegis Flow" },
  { text: "Chaque jour validé dans ce dashboard est une brique indestructible dans la forteresse de ton avenir.", author: "Aegis Flow" },
  { text: "Le jeûne purifie ton corps, la prière élève ton âme, le code matérialise ta vision.", author: "Aegis Flow" },
  { text: "Si tu ressens le vide, remplis-le par la gratitude et l'action acharnée.", author: "Aegis Flow" },
  { text: "Tu as signé pour 210 jours d'immersion totale. Pas de retour en arrière possible. Victoire absolue ou rien.", author: "Aegis Flow" }
];
